export const CALIBRATION_SUCCESS = "CALIBRATION_SUCCESS";
export const CALIBRATION_FAIL = "CALIBRATION_FAIL";
export const PURGE_CALIBRATION = "PURGE_CALIBRATION";
export const SET_EYE_TRACKER = "SET_EYE_TRACKER";
